### ISSUE TITLE
Handle some low hanging fruit

### ISSUE THREAD

**Issue by tshprecher** [tshprecher/antlr_psql#19]
@mebelousov, since we're both committed to getting this done by the end of the year, I think we should start segmenting some of the low hanging fruit so we don't both work on the same things. This week, I'd like to knock the following completions:

```
LISTEN | 0/3 (0.00%)
LOCK | 0/34 (0.00%)
MOVE | 1/10 (10.00%)
NOTIFY | 0/2 (0.00%)
PREPARE | 0/46 (0.00%)
REASSIGN OWNED | 0/4 (0.00%)
REINDEX | 0/6 (0.00%)
RELEASE SAVEPOINT | 0/9 (0.00%)
RESET | 0/49 (0.00%)
REVOKE | 2/77 (2.60%)
ROLLBACK | 0/12 (0.00%)
ROLLBACK PREPARED | 0/4 (0.00%)
ROLLBACK TO SAVEPOINT | 0/10 (0.00%)
SAVEPOINT | 0/22 (0.00%)
SECURITY LABEL | 0/8 (0.00%)
```

They should be easy and bring lots more green into the test coverage status. I'm creating this issue so we don't end up working on the same things.

**Comment by mebelousov** [comment]
Grean! Thank you for planning.

I have implemented PREPARE. Will make PR soon.
https://github.com/mebelousov/antlr_psql/blob/4921e22f9f22d9d4bda5eaf7846240172ff4c7bd/antlr4/PostgreSQLParser.g4#L1121

**Comment by tshprecher** [comment]
I implemented all but `REVOKE` because that one wasn't so low-hanging.
